name: 'Hello World'
description: 'Greet someone'
inputs:
    silo-core-cache-setup: # id of input
        description: 'command to run'
        required: true
        default: 'echo "empty run"'

runs:
    using: 'composite'
    steps:
        #            -   name: Cache cloned submodules
        #                uses: actions/cache@v3
        #                with:
        #                    path: /home/runner/work/silo-contracts-v2/silo-contracts-v2/gitmodules
        #                    key: home-runner-work-silo-contracts-v2-gitmodules

        -   uses: actions/checkout@v3
            with:
                submodules: recursive

        -   name: Cache gitmodules
            uses: actions/cache@v3
            with:
                path: |
                    ~/.npm
                    ./gitmodules/
                key: build-foundry-nightly-2cb875799419c907cc3709e586ece2559e6b340e

        -   name: Cache silo-core contracts
            uses: actions/cache@v3
            with:
                path: ./cache/foundry/out/silo-core
                key: silo-core-contracts-${{ hashFiles('./silo-core/**/*.sol') }}

        #            -   name: Cache silo foundry utils
        #                uses: actions/cache@v3
        #                with:
        #                    path: ./cache/foundry/out/silo-core
        #                    key: silo-foundry-utils-v1

        -   name: Install Foundry
            uses: foundry-rs/foundry-toolchain@v1
            with:
                version: nightly-2cb875799419c907cc3709e586ece2559e6b340e

        -   name: Build silo foundry utils
            working-directory: ./gitmodules/silo-foundry-utils
            run: |
                cargo build --release
                cp target/release/silo-foundry-utils ../../silo-foundry-utils
                ../../silo-foundry-utils --version

        -   name: Executing action
            run: ${{ inputs.silo-core-cache-setup }}

