# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Certora

on:
  push:
    branches: [ master, develop ]
    paths:
      - certora
      - .github/workflows/certora.yml
      - ve-silo/**/*.sol
      - ve-silo/**/*.vy
      - silo-core/**/*.sol
      - silo-oracles/**/*.sol
      - gitmodules/*
      - .gitmodules

  pull_request:
    paths:
      - certora
      - .github/workflows/certora.yml
      - ve-silo/**/*.sol
      - ve-silo/**/*.vy
      - silo-core/**/*.sol
      - silo-oracles/**/*.sol
      - gitmodules/*
      - .gitmodules

jobs:
  ve-silo-foundry:
    strategy:
      fail-fast: true

    name: Deploy & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install the solc-select
        run: |
          pip3 install solc-select

      - name: Install the Certora Prover package
        run: |
          pip3 install certora-cli

      - name: Install/select solidity
        run: |
          solc-select install 0.8.21
          solc-select use 0.8.21

      - name: Print versions
        run: |
          certoraRun --version
          solc --version
