# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Reusable Silo-core workflow for QA

env:
  RPC_MAINNET: ${{ vars.RPC_MAINNET }}
  RPC_ARBITRUM: ${{ vars.RPC_ARBITRUM }}
  RPC_SEPOLIA: ${{ vars.RPC_SEPOLIA }}
  RPC_OPTIMISM: ${{ vars.RPC_OPTIMISM }}
  RPC_ANVIL: ${{ vars.RPC_ANVIL }}
  PRIVATE_KEY: ${{ vars.ANVIL_PRIVATE_KEY }}

on:
  push:
    branches: [ master, develop ]
    paths:
      - silo-core/**/*.sol
      - silo-core/**/*.ts
      - silo-core/**/*.js
      - silo-core/**/*.json
      - silo-oracles/**/*.sol
      - silo-oracles/**/*.ts
      - silo-oracles/**/*.js
      - silo-oracles/**/*.json
      - package.json
      - yarn.lock
      - gitmodules/*
      - .gitmodules
      - .github/workflows/silo-core.yml

  pull_request:
    paths:
      - silo-core/**/*.sol
      - silo-core/**/*.ts
      - silo-core/**/*.js
      - silo-core/**/*.json
      - silo-oracles/**/*.sol
      - silo-oracles/**/*.ts
      - silo-oracles/**/*.js
      - silo-oracles/**/*.json
      - package.json
      - yarn.lock
      - gitmodules/*
      - .gitmodules
      - .github/workflows/silo-core.yml
