# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CORE Quality Test - Echidna

jobs:
  foundry:
    uses: ./.github/workflows/silo-core_.yml
    name: Foundry QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-2cb875799419c907cc3709e586ece2559e6b340e
        
      - name: Build silo foundry utils
        working-directory: ./gitmodules/silo-foundry-utils
        run: |
          cargo build --release
          cp target/release/silo-foundry-utils ../../silo-foundry-utils
          ../../silo-foundry-utils --version

      - name: Run Forge build
        run: |
          git submodule
          forge --version
          FOUNDRY_PROFILE=core forge build --sizes

      - name: Run Forge tests
        run: FOUNDRY_PROFILE=core-test forge test --match-path "**/test/foundry/echidna-findings/*sol" --ffi -vv
