name: Update addresses in Hypernative

on:
  push:
  pull_request:
    paths:
      - silo-core/deploy/silo/_siloDeployments.json
      - silo-core/deployments/**/*.json

jobs:
  hypernative:
    name: Add all silo related addresses to existing monitor.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Build silo foundry utils
        working-directory: ./gitmodules/silo-foundry-utils
        run: |
          cargo build --release
          cp target/release/silo-foundry-utils ../../silo-foundry-utils
          ../../silo-foundry-utils --version

      - name: Run Forge build
        run: |
          git submodule
          forge --version
          FOUNDRY_PROFILE=core forge build --sizes

      - name: Fetch addresses and send request for Sonic
        env:
            RPC_SONIC: ${{ secrets.RPC_SONIC }}
            VERIFIER_URL_SONIC: ${{ secrets.VERIFIER_URL_SONIC }}
            VERIFIER_API_KEY_SONIC: ${{ secrets.VERIFIER_API_KEY_SONIC }}
            RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
            RPC_AVALANCHE: ${{ secrets.RPC_AVALANCHE }}
            HYPERNATIVE_WATCHLIST: ${{ secrets.HYPERNATIVE_WATCHLIST }}
            HYPERNATIVE_CLIENT_ID: ${{ secrets.HYPERNATIVE_CLIENT_ID }}
            HYPERNATIVE_CLIENT_SECRET: ${{ secrets.HYPERNATIVE_CLIENT_SECRET }}
        run: FOUNDRY_PROFILE=core \
          forge script PRINT_ONLY_SILOS=true silo-core/scripts/PrintSiloAddresses.s.sol \
            --ffi --rpc-url $RPC_SONIC | \
            grep 0x | \
            ./silo-core/scripts/hypernative/sendSingleHypernativeRequest.sh sonic

          ./silo-core/scripts/hypernative/printCoreAddresses.sh sonic | \
            ./silo-core/scripts/hypernative/sendSingleHypernativeRequest.sh sonic
