name: Update addresses in Hypernative

env:
  RPC_SONIC: ${{ secrets.RPC_SONIC }}
  VERIFIER_URL_SONIC: ${{ secrets.VERIFIER_URL_SONIC }}
  VERIFIER_API_KEY_SONIC: ${{ secrets.VERIFIER_API_KEY_SONIC }}
  RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
  RPC_AVALANCHE: ${{ secrets.RPC_AVALANCHE }}
  RPC_ARBITRUM: ${{ secrets.RPC_ARBITRUM }}
  HYPERNATIVE_WATCHLIST_SANDBOX: ${{ secrets.HYPERNATIVE_WATCHLIST_SANDBOX }}
  HYPERNATIVE_WATCHLIST_PAUSE: ${{ secrets.HYPERNATIVE_WATCHLIST_PAUSE }}
  HYPERNATIVE_CLIENT_ID: ${{ secrets.HYPERNATIVE_CLIENT_ID }}
  HYPERNATIVE_CLIENT_SECRET: ${{ secrets.HYPERNATIVE_CLIENT_SECRET }}

on:
  push:
    paths:
      - .github/workflows/update-hypernative.yml

jobs:
  hypernative:
    name: Hypernative request for all chains
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run submodule update
        run: git submodule update --init --recursive

      - name: Build silo foundry utils
        working-directory: ./gitmodules/silo-foundry-utils
        run: |
          cargo build --release
          cp target/release/silo-foundry-utils ../../silo-foundry-utils
          ../../silo-foundry-utils --version

      - name: Fetch addresses and send request for Sonic
        run: ./silo-core/scripts/hypernative/runHypernative.sh $RPC_SONIC sonic sonic

      - name: Fetch addresses and send request for Mainnet
        run: ./silo-core/scripts/hypernative/runHypernative.sh $RPC_MAINNET ethereum mainnet

      - name: Fetch addresses and send request for Arbitrum
        run: ./silo-core/scripts/hypernative/runHypernative.sh $RPC_ARBITRUM arbitrum arbitrum_one

      - name: Fetch addresses and send request for Avalanche
        run: ./silo-core/scripts/hypernative/runHypernative.sh $RPC_AVALANCHE avalanche avalanche
